name = "Foundation"
releaseRepo = "https://github.com/zariuq/Foundation"
preferReleaseBuild = true
defaultTargets = ["Foundation"]

[leanOptions]
pp.unicode.fun = true
weak.linter.flexible = true
weak.linter.refine = true
weak.linter.oldObtain = true
weak.linter.style.multiGoal = true

[[require]]
scope = "leanprover"
name = "doc-gen4"
rev = "e2af49a7b7e5e1a9224008c1f15e7aa4f58a4015"

[[require]]
scope = "leanprover-community"
name = "mathlib"
rev = "0df444a360eaa60ab8c11dca51a86af692955474"

[[lean_lib]]
name = "Foundation"

[[lean_lib]]
name = "Vorspiel"

[[lean_exe]]
name = "Zoo_Arith"
root = "Zoo.Arith"
supportInterpreter = true

[[lean_exe]]
name = "Zoo_SetTheory"
root = "Zoo.SetTheory"
supportInterpreter = true

[[lean_exe]]
name = "Zoo_Modal"
root = "Zoo.Modal"
supportInterpreter = true

[[lean_exe]]
name = "Zoo_InterpretabilityLogic"
root = "Zoo.InterpretabilityLogic"
supportInterpreter = true

[[lean_exe]]
name = "Zoo_Propositional"
root = "Zoo.Propositional"
supportInterpreter = true

[[lean_lib]]
name = "Zoo"
